//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.x
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.x DataTemplate.g 2012-12-29 17:43:56

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019

#pragma warning disable 3021

using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

namespace GBRead.Base
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.x")]
[System.CLSCompliant(false)]
public partial class DataTemplateLexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__23=23;
	public const int T__24=24;
	public const int T__25=25;
	public const int T__26=26;
	public const int T__27=27;
	public const int T__28=28;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int T__33=33;
	public const int T__34=34;
	public const int T__35=35;
	public const int T__36=36;
	public const int T__37=37;
	public const int T__38=38;
	public const int T__39=39;
	public const int T__40=40;
	public const int T__41=41;
	public const int T__42=42;
	public const int T__43=43;
	public const int T__44=44;
	public const int T__45=45;
	public const int T__46=46;
	public const int T__47=47;
	public const int T__48=48;
	public const int T__49=49;
	public const int T__50=50;
	public const int T__51=51;
	public const int T__52=52;
	public const int T__53=53;
	public const int T__54=54;
	public const int T__55=55;
	public const int ARG=4;
	public const int ARRLEN=5;
	public const int BIN_DIGIT=6;
	public const int BIN_NUMBER=7;
	public const int COMMENT=8;
	public const int EXPRESSION=9;
	public const int FIXSTRING=10;
	public const int FORMAT=11;
	public const int FORMAT_ARG=12;
	public const int HEX_DIGIT=13;
	public const int HEX_NUMBER=14;
	public const int INT=15;
	public const int LITERAL=16;
	public const int NUMBER=17;
	public const int OCT_DIGIT=18;
	public const int OCT_NUMBER=19;
	public const int ROOT=20;
	public const int VARSTRING=21;
	public const int WS=22;

	private List<ErrInfo> Errors = new List<ErrInfo>();

	public override void DisplayRecognitionError(string[] tokenNames, RecognitionException e)
	{
		string errHeader = GetErrorHeader(e);
		string errMSG = GetErrorMessage(e, tokenNames);
		Errors.Add(new ErrInfo() {errText = errMSG, error = e});
	}

		public List<ErrInfo> GetErrors()
	{
		return Errors;
	}


    // delegates
    // delegators

	public DataTemplateLexer()
	{
		OnCreated();
	}

	public DataTemplateLexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public DataTemplateLexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "DataTemplate.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__23();
	partial void LeaveRule_T__23();

	// $ANTLR start "T__23"
	[GrammarRule("T__23")]
	private void mT__23()
	{
		EnterRule_T__23();
		EnterRule("T__23", 1);
		TraceIn("T__23", 1);
		try
		{
			int _type = T__23;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:25:7: ( '!' )
			DebugEnterAlt(1);
			// DataTemplate.g:25:9: '!'
			{
			DebugLocation(25, 9);
			Match('!'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__23", 1);
			LeaveRule("T__23", 1);
			LeaveRule_T__23();
		}
	}
	// $ANTLR end "T__23"

	partial void EnterRule_T__24();
	partial void LeaveRule_T__24();

	// $ANTLR start "T__24"
	[GrammarRule("T__24")]
	private void mT__24()
	{
		EnterRule_T__24();
		EnterRule("T__24", 2);
		TraceIn("T__24", 2);
		try
		{
			int _type = T__24;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:26:7: ( '!=' )
			DebugEnterAlt(1);
			// DataTemplate.g:26:9: '!='
			{
			DebugLocation(26, 9);
			Match("!="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__24", 2);
			LeaveRule("T__24", 2);
			LeaveRule_T__24();
		}
	}
	// $ANTLR end "T__24"

	partial void EnterRule_T__25();
	partial void LeaveRule_T__25();

	// $ANTLR start "T__25"
	[GrammarRule("T__25")]
	private void mT__25()
	{
		EnterRule_T__25();
		EnterRule("T__25", 3);
		TraceIn("T__25", 3);
		try
		{
			int _type = T__25;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:27:7: ( '%' )
			DebugEnterAlt(1);
			// DataTemplate.g:27:9: '%'
			{
			DebugLocation(27, 9);
			Match('%'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__25", 3);
			LeaveRule("T__25", 3);
			LeaveRule_T__25();
		}
	}
	// $ANTLR end "T__25"

	partial void EnterRule_T__26();
	partial void LeaveRule_T__26();

	// $ANTLR start "T__26"
	[GrammarRule("T__26")]
	private void mT__26()
	{
		EnterRule_T__26();
		EnterRule("T__26", 4);
		TraceIn("T__26", 4);
		try
		{
			int _type = T__26;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:28:7: ( '&&' )
			DebugEnterAlt(1);
			// DataTemplate.g:28:9: '&&'
			{
			DebugLocation(28, 9);
			Match("&&"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__26", 4);
			LeaveRule("T__26", 4);
			LeaveRule_T__26();
		}
	}
	// $ANTLR end "T__26"

	partial void EnterRule_T__27();
	partial void LeaveRule_T__27();

	// $ANTLR start "T__27"
	[GrammarRule("T__27")]
	private void mT__27()
	{
		EnterRule_T__27();
		EnterRule("T__27", 5);
		TraceIn("T__27", 5);
		try
		{
			int _type = T__27;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:29:7: ( '&' )
			DebugEnterAlt(1);
			// DataTemplate.g:29:9: '&'
			{
			DebugLocation(29, 9);
			Match('&'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__27", 5);
			LeaveRule("T__27", 5);
			LeaveRule_T__27();
		}
	}
	// $ANTLR end "T__27"

	partial void EnterRule_T__28();
	partial void LeaveRule_T__28();

	// $ANTLR start "T__28"
	[GrammarRule("T__28")]
	private void mT__28()
	{
		EnterRule_T__28();
		EnterRule("T__28", 6);
		TraceIn("T__28", 6);
		try
		{
			int _type = T__28;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:30:7: ( '(' )
			DebugEnterAlt(1);
			// DataTemplate.g:30:9: '('
			{
			DebugLocation(30, 9);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__28", 6);
			LeaveRule("T__28", 6);
			LeaveRule_T__28();
		}
	}
	// $ANTLR end "T__28"

	partial void EnterRule_T__29();
	partial void LeaveRule_T__29();

	// $ANTLR start "T__29"
	[GrammarRule("T__29")]
	private void mT__29()
	{
		EnterRule_T__29();
		EnterRule("T__29", 7);
		TraceIn("T__29", 7);
		try
		{
			int _type = T__29;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:31:7: ( ')' )
			DebugEnterAlt(1);
			// DataTemplate.g:31:9: ')'
			{
			DebugLocation(31, 9);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__29", 7);
			LeaveRule("T__29", 7);
			LeaveRule_T__29();
		}
	}
	// $ANTLR end "T__29"

	partial void EnterRule_T__30();
	partial void LeaveRule_T__30();

	// $ANTLR start "T__30"
	[GrammarRule("T__30")]
	private void mT__30()
	{
		EnterRule_T__30();
		EnterRule("T__30", 8);
		TraceIn("T__30", 8);
		try
		{
			int _type = T__30;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:32:7: ( '*' )
			DebugEnterAlt(1);
			// DataTemplate.g:32:9: '*'
			{
			DebugLocation(32, 9);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__30", 8);
			LeaveRule("T__30", 8);
			LeaveRule_T__30();
		}
	}
	// $ANTLR end "T__30"

	partial void EnterRule_T__31();
	partial void LeaveRule_T__31();

	// $ANTLR start "T__31"
	[GrammarRule("T__31")]
	private void mT__31()
	{
		EnterRule_T__31();
		EnterRule("T__31", 9);
		TraceIn("T__31", 9);
		try
		{
			int _type = T__31;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:33:7: ( '+' )
			DebugEnterAlt(1);
			// DataTemplate.g:33:9: '+'
			{
			DebugLocation(33, 9);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__31", 9);
			LeaveRule("T__31", 9);
			LeaveRule_T__31();
		}
	}
	// $ANTLR end "T__31"

	partial void EnterRule_T__32();
	partial void LeaveRule_T__32();

	// $ANTLR start "T__32"
	[GrammarRule("T__32")]
	private void mT__32()
	{
		EnterRule_T__32();
		EnterRule("T__32", 10);
		TraceIn("T__32", 10);
		try
		{
			int _type = T__32;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:34:7: ( '-' )
			DebugEnterAlt(1);
			// DataTemplate.g:34:9: '-'
			{
			DebugLocation(34, 9);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__32", 10);
			LeaveRule("T__32", 10);
			LeaveRule_T__32();
		}
	}
	// $ANTLR end "T__32"

	partial void EnterRule_T__33();
	partial void LeaveRule_T__33();

	// $ANTLR start "T__33"
	[GrammarRule("T__33")]
	private void mT__33()
	{
		EnterRule_T__33();
		EnterRule("T__33", 11);
		TraceIn("T__33", 11);
		try
		{
			int _type = T__33;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:35:7: ( '/' )
			DebugEnterAlt(1);
			// DataTemplate.g:35:9: '/'
			{
			DebugLocation(35, 9);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__33", 11);
			LeaveRule("T__33", 11);
			LeaveRule_T__33();
		}
	}
	// $ANTLR end "T__33"

	partial void EnterRule_T__34();
	partial void LeaveRule_T__34();

	// $ANTLR start "T__34"
	[GrammarRule("T__34")]
	private void mT__34()
	{
		EnterRule_T__34();
		EnterRule("T__34", 12);
		TraceIn("T__34", 12);
		try
		{
			int _type = T__34;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:36:7: ( ':' )
			DebugEnterAlt(1);
			// DataTemplate.g:36:9: ':'
			{
			DebugLocation(36, 9);
			Match(':'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__34", 12);
			LeaveRule("T__34", 12);
			LeaveRule_T__34();
		}
	}
	// $ANTLR end "T__34"

	partial void EnterRule_T__35();
	partial void LeaveRule_T__35();

	// $ANTLR start "T__35"
	[GrammarRule("T__35")]
	private void mT__35()
	{
		EnterRule_T__35();
		EnterRule("T__35", 13);
		TraceIn("T__35", 13);
		try
		{
			int _type = T__35;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:37:7: ( ';' )
			DebugEnterAlt(1);
			// DataTemplate.g:37:9: ';'
			{
			DebugLocation(37, 9);
			Match(';'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__35", 13);
			LeaveRule("T__35", 13);
			LeaveRule_T__35();
		}
	}
	// $ANTLR end "T__35"

	partial void EnterRule_T__36();
	partial void LeaveRule_T__36();

	// $ANTLR start "T__36"
	[GrammarRule("T__36")]
	private void mT__36()
	{
		EnterRule_T__36();
		EnterRule("T__36", 14);
		TraceIn("T__36", 14);
		try
		{
			int _type = T__36;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:38:7: ( '<' )
			DebugEnterAlt(1);
			// DataTemplate.g:38:9: '<'
			{
			DebugLocation(38, 9);
			Match('<'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__36", 14);
			LeaveRule("T__36", 14);
			LeaveRule_T__36();
		}
	}
	// $ANTLR end "T__36"

	partial void EnterRule_T__37();
	partial void LeaveRule_T__37();

	// $ANTLR start "T__37"
	[GrammarRule("T__37")]
	private void mT__37()
	{
		EnterRule_T__37();
		EnterRule("T__37", 15);
		TraceIn("T__37", 15);
		try
		{
			int _type = T__37;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:39:7: ( '<<' )
			DebugEnterAlt(1);
			// DataTemplate.g:39:9: '<<'
			{
			DebugLocation(39, 9);
			Match("<<"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__37", 15);
			LeaveRule("T__37", 15);
			LeaveRule_T__37();
		}
	}
	// $ANTLR end "T__37"

	partial void EnterRule_T__38();
	partial void LeaveRule_T__38();

	// $ANTLR start "T__38"
	[GrammarRule("T__38")]
	private void mT__38()
	{
		EnterRule_T__38();
		EnterRule("T__38", 16);
		TraceIn("T__38", 16);
		try
		{
			int _type = T__38;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:40:7: ( '<=' )
			DebugEnterAlt(1);
			// DataTemplate.g:40:9: '<='
			{
			DebugLocation(40, 9);
			Match("<="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__38", 16);
			LeaveRule("T__38", 16);
			LeaveRule_T__38();
		}
	}
	// $ANTLR end "T__38"

	partial void EnterRule_T__39();
	partial void LeaveRule_T__39();

	// $ANTLR start "T__39"
	[GrammarRule("T__39")]
	private void mT__39()
	{
		EnterRule_T__39();
		EnterRule("T__39", 17);
		TraceIn("T__39", 17);
		try
		{
			int _type = T__39;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:41:7: ( '==' )
			DebugEnterAlt(1);
			// DataTemplate.g:41:9: '=='
			{
			DebugLocation(41, 9);
			Match("=="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__39", 17);
			LeaveRule("T__39", 17);
			LeaveRule_T__39();
		}
	}
	// $ANTLR end "T__39"

	partial void EnterRule_T__40();
	partial void LeaveRule_T__40();

	// $ANTLR start "T__40"
	[GrammarRule("T__40")]
	private void mT__40()
	{
		EnterRule_T__40();
		EnterRule("T__40", 18);
		TraceIn("T__40", 18);
		try
		{
			int _type = T__40;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:42:7: ( '>' )
			DebugEnterAlt(1);
			// DataTemplate.g:42:9: '>'
			{
			DebugLocation(42, 9);
			Match('>'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__40", 18);
			LeaveRule("T__40", 18);
			LeaveRule_T__40();
		}
	}
	// $ANTLR end "T__40"

	partial void EnterRule_T__41();
	partial void LeaveRule_T__41();

	// $ANTLR start "T__41"
	[GrammarRule("T__41")]
	private void mT__41()
	{
		EnterRule_T__41();
		EnterRule("T__41", 19);
		TraceIn("T__41", 19);
		try
		{
			int _type = T__41;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:43:7: ( '>=' )
			DebugEnterAlt(1);
			// DataTemplate.g:43:9: '>='
			{
			DebugLocation(43, 9);
			Match(">="); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__41", 19);
			LeaveRule("T__41", 19);
			LeaveRule_T__41();
		}
	}
	// $ANTLR end "T__41"

	partial void EnterRule_T__42();
	partial void LeaveRule_T__42();

	// $ANTLR start "T__42"
	[GrammarRule("T__42")]
	private void mT__42()
	{
		EnterRule_T__42();
		EnterRule("T__42", 20);
		TraceIn("T__42", 20);
		try
		{
			int _type = T__42;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:44:7: ( '>>' )
			DebugEnterAlt(1);
			// DataTemplate.g:44:9: '>>'
			{
			DebugLocation(44, 9);
			Match(">>"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__42", 20);
			LeaveRule("T__42", 20);
			LeaveRule_T__42();
		}
	}
	// $ANTLR end "T__42"

	partial void EnterRule_T__43();
	partial void LeaveRule_T__43();

	// $ANTLR start "T__43"
	[GrammarRule("T__43")]
	private void mT__43()
	{
		EnterRule_T__43();
		EnterRule("T__43", 21);
		TraceIn("T__43", 21);
		try
		{
			int _type = T__43;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:45:7: ( '?' )
			DebugEnterAlt(1);
			// DataTemplate.g:45:9: '?'
			{
			DebugLocation(45, 9);
			Match('?'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__43", 21);
			LeaveRule("T__43", 21);
			LeaveRule_T__43();
		}
	}
	// $ANTLR end "T__43"

	partial void EnterRule_T__44();
	partial void LeaveRule_T__44();

	// $ANTLR start "T__44"
	[GrammarRule("T__44")]
	private void mT__44()
	{
		EnterRule_T__44();
		EnterRule("T__44", 22);
		TraceIn("T__44", 22);
		try
		{
			int _type = T__44;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:46:7: ( '[' )
			DebugEnterAlt(1);
			// DataTemplate.g:46:9: '['
			{
			DebugLocation(46, 9);
			Match('['); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__44", 22);
			LeaveRule("T__44", 22);
			LeaveRule_T__44();
		}
	}
	// $ANTLR end "T__44"

	partial void EnterRule_T__45();
	partial void LeaveRule_T__45();

	// $ANTLR start "T__45"
	[GrammarRule("T__45")]
	private void mT__45()
	{
		EnterRule_T__45();
		EnterRule("T__45", 23);
		TraceIn("T__45", 23);
		try
		{
			int _type = T__45;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:47:7: ( '\\'' )
			DebugEnterAlt(1);
			// DataTemplate.g:47:9: '\\''
			{
			DebugLocation(47, 9);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__45", 23);
			LeaveRule("T__45", 23);
			LeaveRule_T__45();
		}
	}
	// $ANTLR end "T__45"

	partial void EnterRule_T__46();
	partial void LeaveRule_T__46();

	// $ANTLR start "T__46"
	[GrammarRule("T__46")]
	private void mT__46()
	{
		EnterRule_T__46();
		EnterRule("T__46", 24);
		TraceIn("T__46", 24);
		try
		{
			int _type = T__46;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:48:7: ( ']' )
			DebugEnterAlt(1);
			// DataTemplate.g:48:9: ']'
			{
			DebugLocation(48, 9);
			Match(']'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__46", 24);
			LeaveRule("T__46", 24);
			LeaveRule_T__46();
		}
	}
	// $ANTLR end "T__46"

	partial void EnterRule_T__47();
	partial void LeaveRule_T__47();

	// $ANTLR start "T__47"
	[GrammarRule("T__47")]
	private void mT__47()
	{
		EnterRule_T__47();
		EnterRule("T__47", 25);
		TraceIn("T__47", 25);
		try
		{
			int _type = T__47;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:49:7: ( '^' )
			DebugEnterAlt(1);
			// DataTemplate.g:49:9: '^'
			{
			DebugLocation(49, 9);
			Match('^'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__47", 25);
			LeaveRule("T__47", 25);
			LeaveRule_T__47();
		}
	}
	// $ANTLR end "T__47"

	partial void EnterRule_T__48();
	partial void LeaveRule_T__48();

	// $ANTLR start "T__48"
	[GrammarRule("T__48")]
	private void mT__48()
	{
		EnterRule_T__48();
		EnterRule("T__48", 26);
		TraceIn("T__48", 26);
		try
		{
			int _type = T__48;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:50:7: ( 'byte' )
			DebugEnterAlt(1);
			// DataTemplate.g:50:9: 'byte'
			{
			DebugLocation(50, 9);
			Match("byte"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__48", 26);
			LeaveRule("T__48", 26);
			LeaveRule_T__48();
		}
	}
	// $ANTLR end "T__48"

	partial void EnterRule_T__49();
	partial void LeaveRule_T__49();

	// $ANTLR start "T__49"
	[GrammarRule("T__49")]
	private void mT__49()
	{
		EnterRule_T__49();
		EnterRule("T__49", 27);
		TraceIn("T__49", 27);
		try
		{
			int _type = T__49;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:51:7: ( 'dword' )
			DebugEnterAlt(1);
			// DataTemplate.g:51:9: 'dword'
			{
			DebugLocation(51, 9);
			Match("dword"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__49", 27);
			LeaveRule("T__49", 27);
			LeaveRule_T__49();
		}
	}
	// $ANTLR end "T__49"

	partial void EnterRule_T__50();
	partial void LeaveRule_T__50();

	// $ANTLR start "T__50"
	[GrammarRule("T__50")]
	private void mT__50()
	{
		EnterRule_T__50();
		EnterRule("T__50", 28);
		TraceIn("T__50", 28);
		try
		{
			int _type = T__50;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:52:7: ( 'qword' )
			DebugEnterAlt(1);
			// DataTemplate.g:52:9: 'qword'
			{
			DebugLocation(52, 9);
			Match("qword"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__50", 28);
			LeaveRule("T__50", 28);
			LeaveRule_T__50();
		}
	}
	// $ANTLR end "T__50"

	partial void EnterRule_T__51();
	partial void LeaveRule_T__51();

	// $ANTLR start "T__51"
	[GrammarRule("T__51")]
	private void mT__51()
	{
		EnterRule_T__51();
		EnterRule("T__51", 29);
		TraceIn("T__51", 29);
		try
		{
			int _type = T__51;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:53:7: ( 'string' )
			DebugEnterAlt(1);
			// DataTemplate.g:53:9: 'string'
			{
			DebugLocation(53, 9);
			Match("string"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__51", 29);
			LeaveRule("T__51", 29);
			LeaveRule_T__51();
		}
	}
	// $ANTLR end "T__51"

	partial void EnterRule_T__52();
	partial void LeaveRule_T__52();

	// $ANTLR start "T__52"
	[GrammarRule("T__52")]
	private void mT__52()
	{
		EnterRule_T__52();
		EnterRule("T__52", 30);
		TraceIn("T__52", 30);
		try
		{
			int _type = T__52;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:54:7: ( 'word' )
			DebugEnterAlt(1);
			// DataTemplate.g:54:9: 'word'
			{
			DebugLocation(54, 9);
			Match("word"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__52", 30);
			LeaveRule("T__52", 30);
			LeaveRule_T__52();
		}
	}
	// $ANTLR end "T__52"

	partial void EnterRule_T__53();
	partial void LeaveRule_T__53();

	// $ANTLR start "T__53"
	[GrammarRule("T__53")]
	private void mT__53()
	{
		EnterRule_T__53();
		EnterRule("T__53", 31);
		TraceIn("T__53", 31);
		try
		{
			int _type = T__53;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:55:7: ( '|' )
			DebugEnterAlt(1);
			// DataTemplate.g:55:9: '|'
			{
			DebugLocation(55, 9);
			Match('|'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__53", 31);
			LeaveRule("T__53", 31);
			LeaveRule_T__53();
		}
	}
	// $ANTLR end "T__53"

	partial void EnterRule_T__54();
	partial void LeaveRule_T__54();

	// $ANTLR start "T__54"
	[GrammarRule("T__54")]
	private void mT__54()
	{
		EnterRule_T__54();
		EnterRule("T__54", 32);
		TraceIn("T__54", 32);
		try
		{
			int _type = T__54;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:56:7: ( '||' )
			DebugEnterAlt(1);
			// DataTemplate.g:56:9: '||'
			{
			DebugLocation(56, 9);
			Match("||"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__54", 32);
			LeaveRule("T__54", 32);
			LeaveRule_T__54();
		}
	}
	// $ANTLR end "T__54"

	partial void EnterRule_T__55();
	partial void LeaveRule_T__55();

	// $ANTLR start "T__55"
	[GrammarRule("T__55")]
	private void mT__55()
	{
		EnterRule_T__55();
		EnterRule("T__55", 33);
		TraceIn("T__55", 33);
		try
		{
			int _type = T__55;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:57:7: ( '~' )
			DebugEnterAlt(1);
			// DataTemplate.g:57:9: '~'
			{
			DebugLocation(57, 9);
			Match('~'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__55", 33);
			LeaveRule("T__55", 33);
			LeaveRule_T__55();
		}
	}
	// $ANTLR end "T__55"

	partial void EnterRule_FORMAT_ARG();
	partial void LeaveRule_FORMAT_ARG();

	// $ANTLR start "FORMAT_ARG"
	[GrammarRule("FORMAT_ARG")]
	private void mFORMAT_ARG()
	{
		EnterRule_FORMAT_ARG();
		EnterRule("FORMAT_ARG", 34);
		TraceIn("FORMAT_ARG", 34);
		try
		{
			int _type = FORMAT_ARG;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:87:13: ( ( 'd' | 'b' | 'h' | 'o' | 'g' )+ )
			DebugEnterAlt(1);
			// DataTemplate.g:87:15: ( 'd' | 'b' | 'h' | 'o' | 'g' )+
			{
			DebugLocation(87, 15);
			// DataTemplate.g:87:15: ( 'd' | 'b' | 'h' | 'o' | 'g' )+
			int cnt1=0;
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if ((LA1_1=='b'||LA1_1=='d'||(LA1_1>='g' && LA1_1<='h')||LA1_1=='o'))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch (alt1)
				{
				case 1:
					DebugEnterAlt(1);
					// DataTemplate.g:
					{
					DebugLocation(87, 15);
					input.Consume();


					}
					break;

				default:
					if (cnt1 >= 1)
						goto loop1;

					EarlyExitException eee1 = new EarlyExitException( 1, input );
					DebugRecognitionException(eee1);
					throw eee1;
				}
				cnt1++;
			}
			loop1:
				;

			} finally { DebugExitSubRule(1); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FORMAT_ARG", 34);
			LeaveRule("FORMAT_ARG", 34);
			LeaveRule_FORMAT_ARG();
		}
	}
	// $ANTLR end "FORMAT_ARG"

	partial void EnterRule_NUMBER();
	partial void LeaveRule_NUMBER();

	// $ANTLR start "NUMBER"
	[GrammarRule("NUMBER")]
	private void mNUMBER()
	{
		EnterRule_NUMBER();
		EnterRule("NUMBER", 35);
		TraceIn("NUMBER", 35);
		try
		{
			int _type = NUMBER;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:107:10: ( INT | HEX_NUMBER | BIN_NUMBER | OCT_NUMBER )
			int alt2=4;
			try { DebugEnterDecision(2, false);
			switch (input.LA(1))
			{
			case '0':
				{
				switch (input.LA(2))
				{
				case 'x':
					{
					alt2 = 2;
					}
					break;
				case 'b':
					{
					alt2 = 3;
					}
					break;
				case 'o':
					{
					alt2 = 4;
					}
					break;
				default:
					alt2=1;
					break;

				}

				}
				break;
			case '$':
				{
				alt2 = 2;
				}
				break;
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
				{
				alt2 = 1;
				}
				break;
			case '%':
				{
				alt2 = 3;
				}
				break;
			case '&':
				{
				alt2 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// DataTemplate.g:107:12: INT
				{
				DebugLocation(107, 12);
				mINT(); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// DataTemplate.g:108:7: HEX_NUMBER
				{
				DebugLocation(108, 7);
				mHEX_NUMBER(); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// DataTemplate.g:109:7: BIN_NUMBER
				{
				DebugLocation(109, 7);
				mBIN_NUMBER(); 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// DataTemplate.g:110:7: OCT_NUMBER
				{
				DebugLocation(110, 7);
				mOCT_NUMBER(); 

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUMBER", 35);
			LeaveRule("NUMBER", 35);
			LeaveRule_NUMBER();
		}
	}
	// $ANTLR end "NUMBER"

	partial void EnterRule_COMMENT();
	partial void LeaveRule_COMMENT();

	// $ANTLR start "COMMENT"
	[GrammarRule("COMMENT")]
	private void mCOMMENT()
	{
		EnterRule_COMMENT();
		EnterRule("COMMENT", 36);
		TraceIn("COMMENT", 36);
		try
		{
			int _type = COMMENT;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:112:11: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' | '/*' ( options {greedy=false; } : . )* '*/' )
			int alt6=2;
			try { DebugEnterDecision(6, false);
			int LA6_1 = input.LA(1);

			if ((LA6_1=='/'))
			{
				int LA6_2 = input.LA(2);

				if ((LA6_2=='/'))
				{
					alt6 = 1;
				}
				else if ((LA6_2=='*'))
				{
					alt6 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 6, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 6, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// DataTemplate.g:112:15: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
				{
				DebugLocation(112, 15);
				Match("//"); 

				DebugLocation(112, 20);
				// DataTemplate.g:112:20: (~ ( '\\n' | '\\r' ) )*
				try { DebugEnterSubRule(3);
				while (true)
				{
					int alt3=2;
					try { DebugEnterDecision(3, false);
					int LA3_1 = input.LA(1);

					if (((LA3_1>='\u0000' && LA3_1<='\t')||(LA3_1>='\u000B' && LA3_1<='\f')||(LA3_1>='\u000E' && LA3_1<='\uFFFF')))
					{
						alt3 = 1;
					}


					} finally { DebugExitDecision(3); }
					switch ( alt3 )
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(112, 20);
						input.Consume();


						}
						break;

					default:
						goto loop3;
					}
				}

				loop3:
					;

				} finally { DebugExitSubRule(3); }

				DebugLocation(112, 34);
				// DataTemplate.g:112:34: ( '\\r' )?
				int alt4=2;
				try { DebugEnterSubRule(4);
				try { DebugEnterDecision(4, false);
				int LA4_1 = input.LA(1);

				if ((LA4_1=='\r'))
				{
					alt4 = 1;
				}
				} finally { DebugExitDecision(4); }
				switch (alt4)
				{
				case 1:
					DebugEnterAlt(1);
					// DataTemplate.g:112:34: '\\r'
					{
					DebugLocation(112, 34);
					Match('\r'); 

					}
					break;

				}
				} finally { DebugExitSubRule(4); }

				DebugLocation(112, 40);
				Match('\n'); 
				DebugLocation(112, 45);
				_channel=Hidden;

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// DataTemplate.g:113:9: '/*' ( options {greedy=false; } : . )* '*/'
				{
				DebugLocation(113, 9);
				Match("/*"); 

				DebugLocation(113, 14);
				// DataTemplate.g:113:14: ( options {greedy=false; } : . )*
				try { DebugEnterSubRule(5);
				while (true)
				{
					int alt5=2;
					try { DebugEnterDecision(5, false);
					int LA5_1 = input.LA(1);

					if ((LA5_1=='*'))
					{
						int LA5_2 = input.LA(2);

						if ((LA5_2=='/'))
						{
							alt5 = 2;
						}
						else if (((LA5_2>='\u0000' && LA5_2<='.')||(LA5_2>='0' && LA5_2<='\uFFFF')))
						{
							alt5 = 1;
						}


					}
					else if (((LA5_1>='\u0000' && LA5_1<=')')||(LA5_1>='+' && LA5_1<='\uFFFF')))
					{
						alt5 = 1;
					}


					} finally { DebugExitDecision(5); }
					switch ( alt5 )
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:113:42: .
						{
						DebugLocation(113, 42);
						MatchAny(); 

						}
						break;

					default:
						goto loop5;
					}
				}

				loop5:
					;

				} finally { DebugExitSubRule(5); }

				DebugLocation(113, 47);
				Match("*/"); 

				DebugLocation(113, 52);
				_channel=Hidden;

				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("COMMENT", 36);
			LeaveRule("COMMENT", 36);
			LeaveRule_COMMENT();
		}
	}
	// $ANTLR end "COMMENT"

	partial void EnterRule_INT();
	partial void LeaveRule_INT();

	// $ANTLR start "INT"
	[GrammarRule("INT")]
	private void mINT()
	{
		EnterRule_INT();
		EnterRule("INT", 37);
		TraceIn("INT", 37);
		try
		{
			// DataTemplate.g:117:8: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// DataTemplate.g:117:10: ( '0' .. '9' )+
			{
			DebugLocation(117, 10);
			// DataTemplate.g:117:10: ( '0' .. '9' )+
			int cnt7=0;
			try { DebugEnterSubRule(7);
			while (true)
			{
				int alt7=2;
				try { DebugEnterDecision(7, false);
				int LA7_1 = input.LA(1);

				if (((LA7_1>='0' && LA7_1<='9')))
				{
					alt7 = 1;
				}


				} finally { DebugExitDecision(7); }
				switch (alt7)
				{
				case 1:
					DebugEnterAlt(1);
					// DataTemplate.g:
					{
					DebugLocation(117, 10);
					input.Consume();


					}
					break;

				default:
					if (cnt7 >= 1)
						goto loop7;

					EarlyExitException eee7 = new EarlyExitException( 7, input );
					DebugRecognitionException(eee7);
					throw eee7;
				}
				cnt7++;
			}
			loop7:
				;

			} finally { DebugExitSubRule(7); }


			}

		}
		finally
		{
			TraceOut("INT", 37);
			LeaveRule("INT", 37);
			LeaveRule_INT();
		}
	}
	// $ANTLR end "INT"

	partial void EnterRule_HEX_NUMBER();
	partial void LeaveRule_HEX_NUMBER();

	// $ANTLR start "HEX_NUMBER"
	[GrammarRule("HEX_NUMBER")]
	private void mHEX_NUMBER()
	{
		EnterRule_HEX_NUMBER();
		EnterRule("HEX_NUMBER", 38);
		TraceIn("HEX_NUMBER", 38);
		try
		{
			// DataTemplate.g:119:13: ( '$' ( HEX_DIGIT )+ | '0' 'x' ( HEX_DIGIT )+ )
			int alt10=2;
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if ((LA10_1=='$'))
			{
				alt10 = 1;
			}
			else if ((LA10_1=='0'))
			{
				alt10 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 10, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// DataTemplate.g:119:15: '$' ( HEX_DIGIT )+
				{
				DebugLocation(119, 15);
				Match('$'); 
				DebugLocation(119, 18);
				// DataTemplate.g:119:18: ( HEX_DIGIT )+
				int cnt8=0;
				try { DebugEnterSubRule(8);
				while (true)
				{
					int alt8=2;
					try { DebugEnterDecision(8, false);
					int LA8_1 = input.LA(1);

					if (((LA8_1>='0' && LA8_1<='9')||(LA8_1>='a' && LA8_1<='f')))
					{
						alt8 = 1;
					}


					} finally { DebugExitDecision(8); }
					switch (alt8)
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(119, 18);
						input.Consume();


						}
						break;

					default:
						if (cnt8 >= 1)
							goto loop8;

						EarlyExitException eee8 = new EarlyExitException( 8, input );
						DebugRecognitionException(eee8);
						throw eee8;
					}
					cnt8++;
				}
				loop8:
					;

				} finally { DebugExitSubRule(8); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// DataTemplate.g:120:7: '0' 'x' ( HEX_DIGIT )+
				{
				DebugLocation(120, 7);
				Match('0'); 
				DebugLocation(120, 10);
				Match('x'); 
				DebugLocation(120, 13);
				// DataTemplate.g:120:13: ( HEX_DIGIT )+
				int cnt9=0;
				try { DebugEnterSubRule(9);
				while (true)
				{
					int alt9=2;
					try { DebugEnterDecision(9, false);
					int LA9_1 = input.LA(1);

					if (((LA9_1>='0' && LA9_1<='9')||(LA9_1>='a' && LA9_1<='f')))
					{
						alt9 = 1;
					}


					} finally { DebugExitDecision(9); }
					switch (alt9)
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(120, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt9 >= 1)
							goto loop9;

						EarlyExitException eee9 = new EarlyExitException( 9, input );
						DebugRecognitionException(eee9);
						throw eee9;
					}
					cnt9++;
				}
				loop9:
					;

				} finally { DebugExitSubRule(9); }


				}
				break;

			}
		}
		finally
		{
			TraceOut("HEX_NUMBER", 38);
			LeaveRule("HEX_NUMBER", 38);
			LeaveRule_HEX_NUMBER();
		}
	}
	// $ANTLR end "HEX_NUMBER"

	partial void EnterRule_BIN_NUMBER();
	partial void LeaveRule_BIN_NUMBER();

	// $ANTLR start "BIN_NUMBER"
	[GrammarRule("BIN_NUMBER")]
	private void mBIN_NUMBER()
	{
		EnterRule_BIN_NUMBER();
		EnterRule("BIN_NUMBER", 39);
		TraceIn("BIN_NUMBER", 39);
		try
		{
			// DataTemplate.g:122:13: ( '%' ( BIN_DIGIT )+ | '0' 'b' ( BIN_DIGIT )+ )
			int alt13=2;
			try { DebugEnterDecision(13, false);
			int LA13_1 = input.LA(1);

			if ((LA13_1=='%'))
			{
				alt13 = 1;
			}
			else if ((LA13_1=='0'))
			{
				alt13 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// DataTemplate.g:122:15: '%' ( BIN_DIGIT )+
				{
				DebugLocation(122, 15);
				Match('%'); 
				DebugLocation(122, 18);
				// DataTemplate.g:122:18: ( BIN_DIGIT )+
				int cnt11=0;
				try { DebugEnterSubRule(11);
				while (true)
				{
					int alt11=2;
					try { DebugEnterDecision(11, false);
					int LA11_1 = input.LA(1);

					if (((LA11_1>='0' && LA11_1<='1')))
					{
						alt11 = 1;
					}


					} finally { DebugExitDecision(11); }
					switch (alt11)
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(122, 18);
						input.Consume();


						}
						break;

					default:
						if (cnt11 >= 1)
							goto loop11;

						EarlyExitException eee11 = new EarlyExitException( 11, input );
						DebugRecognitionException(eee11);
						throw eee11;
					}
					cnt11++;
				}
				loop11:
					;

				} finally { DebugExitSubRule(11); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// DataTemplate.g:123:7: '0' 'b' ( BIN_DIGIT )+
				{
				DebugLocation(123, 7);
				Match('0'); 
				DebugLocation(123, 10);
				Match('b'); 
				DebugLocation(123, 13);
				// DataTemplate.g:123:13: ( BIN_DIGIT )+
				int cnt12=0;
				try { DebugEnterSubRule(12);
				while (true)
				{
					int alt12=2;
					try { DebugEnterDecision(12, false);
					int LA12_1 = input.LA(1);

					if (((LA12_1>='0' && LA12_1<='1')))
					{
						alt12 = 1;
					}


					} finally { DebugExitDecision(12); }
					switch (alt12)
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(123, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt12 >= 1)
							goto loop12;

						EarlyExitException eee12 = new EarlyExitException( 12, input );
						DebugRecognitionException(eee12);
						throw eee12;
					}
					cnt12++;
				}
				loop12:
					;

				} finally { DebugExitSubRule(12); }


				}
				break;

			}
		}
		finally
		{
			TraceOut("BIN_NUMBER", 39);
			LeaveRule("BIN_NUMBER", 39);
			LeaveRule_BIN_NUMBER();
		}
	}
	// $ANTLR end "BIN_NUMBER"

	partial void EnterRule_OCT_NUMBER();
	partial void LeaveRule_OCT_NUMBER();

	// $ANTLR start "OCT_NUMBER"
	[GrammarRule("OCT_NUMBER")]
	private void mOCT_NUMBER()
	{
		EnterRule_OCT_NUMBER();
		EnterRule("OCT_NUMBER", 40);
		TraceIn("OCT_NUMBER", 40);
		try
		{
			// DataTemplate.g:125:13: ( '&' ( OCT_DIGIT )+ | '0' 'o' ( OCT_DIGIT )+ )
			int alt16=2;
			try { DebugEnterDecision(16, false);
			int LA16_1 = input.LA(1);

			if ((LA16_1=='&'))
			{
				alt16 = 1;
			}
			else if ((LA16_1=='0'))
			{
				alt16 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 16, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(16); }
			switch (alt16)
			{
			case 1:
				DebugEnterAlt(1);
				// DataTemplate.g:125:15: '&' ( OCT_DIGIT )+
				{
				DebugLocation(125, 15);
				Match('&'); 
				DebugLocation(125, 18);
				// DataTemplate.g:125:18: ( OCT_DIGIT )+
				int cnt14=0;
				try { DebugEnterSubRule(14);
				while (true)
				{
					int alt14=2;
					try { DebugEnterDecision(14, false);
					int LA14_1 = input.LA(1);

					if (((LA14_1>='0' && LA14_1<='7')))
					{
						alt14 = 1;
					}


					} finally { DebugExitDecision(14); }
					switch (alt14)
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(125, 18);
						input.Consume();


						}
						break;

					default:
						if (cnt14 >= 1)
							goto loop14;

						EarlyExitException eee14 = new EarlyExitException( 14, input );
						DebugRecognitionException(eee14);
						throw eee14;
					}
					cnt14++;
				}
				loop14:
					;

				} finally { DebugExitSubRule(14); }


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// DataTemplate.g:126:7: '0' 'o' ( OCT_DIGIT )+
				{
				DebugLocation(126, 7);
				Match('0'); 
				DebugLocation(126, 10);
				Match('o'); 
				DebugLocation(126, 13);
				// DataTemplate.g:126:13: ( OCT_DIGIT )+
				int cnt15=0;
				try { DebugEnterSubRule(15);
				while (true)
				{
					int alt15=2;
					try { DebugEnterDecision(15, false);
					int LA15_1 = input.LA(1);

					if (((LA15_1>='0' && LA15_1<='7')))
					{
						alt15 = 1;
					}


					} finally { DebugExitDecision(15); }
					switch (alt15)
					{
					case 1:
						DebugEnterAlt(1);
						// DataTemplate.g:
						{
						DebugLocation(126, 13);
						input.Consume();


						}
						break;

					default:
						if (cnt15 >= 1)
							goto loop15;

						EarlyExitException eee15 = new EarlyExitException( 15, input );
						DebugRecognitionException(eee15);
						throw eee15;
					}
					cnt15++;
				}
				loop15:
					;

				} finally { DebugExitSubRule(15); }


				}
				break;

			}
		}
		finally
		{
			TraceOut("OCT_NUMBER", 40);
			LeaveRule("OCT_NUMBER", 40);
			LeaveRule_OCT_NUMBER();
		}
	}
	// $ANTLR end "OCT_NUMBER"

	partial void EnterRule_HEX_DIGIT();
	partial void LeaveRule_HEX_DIGIT();

	// $ANTLR start "HEX_DIGIT"
	[GrammarRule("HEX_DIGIT")]
	private void mHEX_DIGIT()
	{
		EnterRule_HEX_DIGIT();
		EnterRule("HEX_DIGIT", 41);
		TraceIn("HEX_DIGIT", 41);
		try
		{
			// DataTemplate.g:128:13: ( ( '0' .. '9' | 'a' .. 'f' ) )
			DebugEnterAlt(1);
			// DataTemplate.g:
			{
			DebugLocation(128, 13);
			if ((input.LA(1)>='0' && input.LA(1)<='9')||(input.LA(1)>='a' && input.LA(1)<='f'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("HEX_DIGIT", 41);
			LeaveRule("HEX_DIGIT", 41);
			LeaveRule_HEX_DIGIT();
		}
	}
	// $ANTLR end "HEX_DIGIT"

	partial void EnterRule_OCT_DIGIT();
	partial void LeaveRule_OCT_DIGIT();

	// $ANTLR start "OCT_DIGIT"
	[GrammarRule("OCT_DIGIT")]
	private void mOCT_DIGIT()
	{
		EnterRule_OCT_DIGIT();
		EnterRule("OCT_DIGIT", 42);
		TraceIn("OCT_DIGIT", 42);
		try
		{
			// DataTemplate.g:130:12: ( ( '0' .. '7' ) )
			DebugEnterAlt(1);
			// DataTemplate.g:
			{
			DebugLocation(130, 12);
			if ((input.LA(1)>='0' && input.LA(1)<='7'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("OCT_DIGIT", 42);
			LeaveRule("OCT_DIGIT", 42);
			LeaveRule_OCT_DIGIT();
		}
	}
	// $ANTLR end "OCT_DIGIT"

	partial void EnterRule_BIN_DIGIT();
	partial void LeaveRule_BIN_DIGIT();

	// $ANTLR start "BIN_DIGIT"
	[GrammarRule("BIN_DIGIT")]
	private void mBIN_DIGIT()
	{
		EnterRule_BIN_DIGIT();
		EnterRule("BIN_DIGIT", 43);
		TraceIn("BIN_DIGIT", 43);
		try
		{
			// DataTemplate.g:132:12: ( ( '0' .. '1' ) )
			DebugEnterAlt(1);
			// DataTemplate.g:
			{
			DebugLocation(132, 12);
			if ((input.LA(1)>='0' && input.LA(1)<='1'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

		}
		finally
		{
			TraceOut("BIN_DIGIT", 43);
			LeaveRule("BIN_DIGIT", 43);
			LeaveRule_BIN_DIGIT();
		}
	}
	// $ANTLR end "BIN_DIGIT"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 44);
		TraceIn("WS", 44);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// DataTemplate.g:133:7: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
			DebugEnterAlt(1);
			// DataTemplate.g:133:11: ( ' ' | '\\t' | '\\r' | '\\n' )
			{
			DebugLocation(133, 11);
			if ((input.LA(1)>='\t' && input.LA(1)<='\n')||input.LA(1)=='\r'||input.LA(1)==' ')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(133, 36);
			_channel=Hidden;

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 44);
			LeaveRule("WS", 44);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	public override void mTokens()
	{
		// DataTemplate.g:1:8: ( T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | T__46 | T__47 | T__48 | T__49 | T__50 | T__51 | T__52 | T__53 | T__54 | T__55 | FORMAT_ARG | NUMBER | COMMENT | WS )
		int alt17=37;
		try { DebugEnterDecision(17, false);
		switch (input.LA(1))
		{
		case '!':
			{
			int LA17_2 = input.LA(2);

			if ((LA17_2=='='))
			{
				alt17 = 2;
			}
			else
			{
				alt17 = 1;
			}
			}
			break;
		case '%':
			{
			int LA17_2 = input.LA(2);

			if (((LA17_2>='0' && LA17_2<='1')))
			{
				alt17 = 35;
			}
			else
			{
				alt17 = 3;
			}
			}
			break;
		case '&':
			{
			switch (input.LA(2))
			{
			case '&':
				{
				alt17 = 4;
				}
				break;
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
				{
				alt17 = 35;
				}
				break;
			default:
				alt17=5;
				break;

			}

			}
			break;
		case '(':
			{
			alt17 = 6;
			}
			break;
		case ')':
			{
			alt17 = 7;
			}
			break;
		case '*':
			{
			alt17 = 8;
			}
			break;
		case '+':
			{
			alt17 = 9;
			}
			break;
		case '-':
			{
			alt17 = 10;
			}
			break;
		case '/':
			{
			int LA17_2 = input.LA(2);

			if ((LA17_2=='*'||LA17_2=='/'))
			{
				alt17 = 36;
			}
			else
			{
				alt17 = 11;
			}
			}
			break;
		case ':':
			{
			alt17 = 12;
			}
			break;
		case ';':
			{
			alt17 = 13;
			}
			break;
		case '<':
			{
			switch (input.LA(2))
			{
			case '<':
				{
				alt17 = 15;
				}
				break;
			case '=':
				{
				alt17 = 16;
				}
				break;
			default:
				alt17=14;
				break;

			}

			}
			break;
		case '=':
			{
			alt17 = 17;
			}
			break;
		case '>':
			{
			switch (input.LA(2))
			{
			case '=':
				{
				alt17 = 19;
				}
				break;
			case '>':
				{
				alt17 = 20;
				}
				break;
			default:
				alt17=18;
				break;

			}

			}
			break;
		case '?':
			{
			alt17 = 21;
			}
			break;
		case '[':
			{
			alt17 = 22;
			}
			break;
		case '\'':
			{
			alt17 = 23;
			}
			break;
		case ']':
			{
			alt17 = 24;
			}
			break;
		case '^':
			{
			alt17 = 25;
			}
			break;
		case 'b':
			{
			int LA17_2 = input.LA(2);

			if ((LA17_2=='y'))
			{
				alt17 = 26;
			}
			else
			{
				alt17 = 34;
			}
			}
			break;
		case 'd':
			{
			int LA17_2 = input.LA(2);

			if ((LA17_2=='w'))
			{
				alt17 = 27;
			}
			else
			{
				alt17 = 34;
			}
			}
			break;
		case 'q':
			{
			alt17 = 28;
			}
			break;
		case 's':
			{
			alt17 = 29;
			}
			break;
		case 'w':
			{
			alt17 = 30;
			}
			break;
		case '|':
			{
			int LA17_2 = input.LA(2);

			if ((LA17_2=='|'))
			{
				alt17 = 32;
			}
			else
			{
				alt17 = 31;
			}
			}
			break;
		case '~':
			{
			alt17 = 33;
			}
			break;
		case 'g':
		case 'h':
		case 'o':
			{
			alt17 = 34;
			}
			break;
		case '$':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			{
			alt17 = 35;
			}
			break;
		case '\t':
		case '\n':
		case '\r':
		case ' ':
			{
			alt17 = 37;
			}
			break;
		default:
			{
				NoViableAltException nvae = new NoViableAltException("", 17, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
		}

		} finally { DebugExitDecision(17); }
		switch (alt17)
		{
		case 1:
			DebugEnterAlt(1);
			// DataTemplate.g:1:10: T__23
			{
			DebugLocation(1, 10);
			mT__23(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// DataTemplate.g:1:16: T__24
			{
			DebugLocation(1, 16);
			mT__24(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// DataTemplate.g:1:22: T__25
			{
			DebugLocation(1, 22);
			mT__25(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// DataTemplate.g:1:28: T__26
			{
			DebugLocation(1, 28);
			mT__26(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// DataTemplate.g:1:34: T__27
			{
			DebugLocation(1, 34);
			mT__27(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// DataTemplate.g:1:40: T__28
			{
			DebugLocation(1, 40);
			mT__28(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// DataTemplate.g:1:46: T__29
			{
			DebugLocation(1, 46);
			mT__29(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// DataTemplate.g:1:52: T__30
			{
			DebugLocation(1, 52);
			mT__30(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// DataTemplate.g:1:58: T__31
			{
			DebugLocation(1, 58);
			mT__31(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// DataTemplate.g:1:64: T__32
			{
			DebugLocation(1, 64);
			mT__32(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// DataTemplate.g:1:70: T__33
			{
			DebugLocation(1, 70);
			mT__33(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// DataTemplate.g:1:76: T__34
			{
			DebugLocation(1, 76);
			mT__34(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// DataTemplate.g:1:82: T__35
			{
			DebugLocation(1, 82);
			mT__35(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// DataTemplate.g:1:88: T__36
			{
			DebugLocation(1, 88);
			mT__36(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// DataTemplate.g:1:94: T__37
			{
			DebugLocation(1, 94);
			mT__37(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// DataTemplate.g:1:100: T__38
			{
			DebugLocation(1, 100);
			mT__38(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// DataTemplate.g:1:106: T__39
			{
			DebugLocation(1, 106);
			mT__39(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// DataTemplate.g:1:112: T__40
			{
			DebugLocation(1, 112);
			mT__40(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// DataTemplate.g:1:118: T__41
			{
			DebugLocation(1, 118);
			mT__41(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// DataTemplate.g:1:124: T__42
			{
			DebugLocation(1, 124);
			mT__42(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// DataTemplate.g:1:130: T__43
			{
			DebugLocation(1, 130);
			mT__43(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// DataTemplate.g:1:136: T__44
			{
			DebugLocation(1, 136);
			mT__44(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// DataTemplate.g:1:142: T__45
			{
			DebugLocation(1, 142);
			mT__45(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// DataTemplate.g:1:148: T__46
			{
			DebugLocation(1, 148);
			mT__46(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// DataTemplate.g:1:154: T__47
			{
			DebugLocation(1, 154);
			mT__47(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// DataTemplate.g:1:160: T__48
			{
			DebugLocation(1, 160);
			mT__48(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// DataTemplate.g:1:166: T__49
			{
			DebugLocation(1, 166);
			mT__49(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// DataTemplate.g:1:172: T__50
			{
			DebugLocation(1, 172);
			mT__50(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// DataTemplate.g:1:178: T__51
			{
			DebugLocation(1, 178);
			mT__51(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// DataTemplate.g:1:184: T__52
			{
			DebugLocation(1, 184);
			mT__52(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// DataTemplate.g:1:190: T__53
			{
			DebugLocation(1, 190);
			mT__53(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// DataTemplate.g:1:196: T__54
			{
			DebugLocation(1, 196);
			mT__54(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// DataTemplate.g:1:202: T__55
			{
			DebugLocation(1, 202);
			mT__55(); 

			}
			break;
		case 34:
			DebugEnterAlt(34);
			// DataTemplate.g:1:208: FORMAT_ARG
			{
			DebugLocation(1, 208);
			mFORMAT_ARG(); 

			}
			break;
		case 35:
			DebugEnterAlt(35);
			// DataTemplate.g:1:219: NUMBER
			{
			DebugLocation(1, 219);
			mNUMBER(); 

			}
			break;
		case 36:
			DebugEnterAlt(36);
			// DataTemplate.g:1:226: COMMENT
			{
			DebugLocation(1, 226);
			mCOMMENT(); 

			}
			break;
		case 37:
			DebugEnterAlt(37);
			// DataTemplate.g:1:234: WS
			{
			DebugLocation(1, 234);
			mWS(); 

			}
			break;

		}

	}


	#region DFA

	protected override void InitDFAs()
	{
		base.InitDFAs();
	}

 
	#endregion

}

} // namespace GBRead.Base
